#!/bin/sh
#
# micrun - A scirpt to run specific commands on the MIC
#          The script switches to CWD and copies environment variables designated 
#          by the prefix set by MIC_ENV_PREFIX ('MIC_' is the default prefix)
#
# Other parameters:
# MICRUN_HOST sets the hostname of the MIC card for offloading (default mic0)
# MICRUN_VERBOSE if set, prints verbose output

if [ -n "${MICRUN_DISABLE}" ]
then
        echo "Tried executing MIC binary on host but MICRUN_DISABLE is set. Exiting..."
	exit
fi



export MICRUN_HOST=node1-mic0
if [ -z "${MICRUN_HOST}" ] 
then 
	export MICRUN_HOST=node1-mic1
fi

if [ "${MICRUN_VERBOSE}" ] 
then
        echo MICRUN Host: $MICRUN_HOST Command: $@ >&2 
fi

if [ -z "${MIC_ENV_PREFIX}" ] 
then
    export MIC_ENV_PREFIX=MIC
fi

MICRUN_ENV=`env | grep -i ^${MIC_ENV_PREFIX}_ | grep -v MIC_ENV_PREFIX | awk -vORS=' ' -v pfx=${MIC_ENV_PREFIX} -F= '{b=$1; a=substr($1,length(pfx)+2,length($1)); print "export "a"="$2";" }'`

starttime=`date`

rc=0

path=`pwd|sed 's/\/data//g'`
# echo $path
ssh -o StrictHostKeyChecking=no $MICRUN_HOST "ulimit -s unlimited; cd $path; $MICRUN_ENV $@"  || rc=$?
# echo ssh -o StrictHostKeyChecking=no $MICRUN_HOST "cd \"$(pwd)\"; $MICRUN_ENV \'$@\'"
endtime=`date`
user=`whoami`

#Uncomment for debugging
#echo "ssh -o StrictHostKeyChecking=no $MICRUN_HOST \"cd $(pwd); $MICRUN_ENV $@\" | rc: $rc | user: $user | start: $starttime | end: $endtime" >> /tmp/micrun.debug
exit $rc
